2025-04-10 19:13:56,290:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:13:56,290:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:13:56,290:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:13:56,290:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:24:15,572:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:24:15,579:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:24:15,579:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:24:15,579:WARNING:
'cuml' is a soft dependency and not included in the pycaret installation. Please run: `pip install cuml` to install.
2025-04-10 19:31:08,147:INFO:PyCaret ClassificationExperiment
2025-04-10 19:31:08,147:INFO:Logging name: clf-default-name
2025-04-10 19:31:08,147:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-04-10 19:31:08,147:INFO:version 3.3.2
2025-04-10 19:31:08,147:INFO:Initializing setup()
2025-04-10 19:31:08,147:INFO:self.USI: e00e
2025-04-10 19:31:08,147:INFO:self._variable_keys: {'pipeline', 'X_train', 'y_test', 'fold_groups_param', 'is_multiclass', 'html_param', 'y_train', 'fix_imbalance', 'fold_shuffle_param', 'exp_name_log', 'fold_generator', 'data', 'target_param', 'gpu_n_jobs_param', 'logging_param', 'idx', 'log_plots_param', 'X_test', 'y', 'seed', 'gpu_param', 'X', '_available_plots', 'USI', 'n_jobs_param', '_ml_usecase', 'memory', 'exp_id'}
2025-04-10 19:31:08,147:INFO:Checking environment
2025-04-10 19:31:08,147:INFO:python_version: 3.11.7
2025-04-10 19:31:08,147:INFO:python_build: ('main', 'Dec 15 2023 18:05:47')
2025-04-10 19:31:08,147:INFO:machine: AMD64
2025-04-10 19:31:08,147:INFO:platform: Windows-10-10.0.22631-SP0
2025-04-10 19:31:08,151:INFO:Memory: svmem(total=34111008768, available=15966064640, percent=53.2, used=18144944128, free=15966064640)
2025-04-10 19:31:08,151:INFO:Physical Core: 14
2025-04-10 19:31:08,152:INFO:Logical Core: 20
2025-04-10 19:31:08,152:INFO:Checking libraries
2025-04-10 19:31:08,152:INFO:System:
2025-04-10 19:31:08,152:INFO:    python: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
2025-04-10 19:31:08,152:INFO:executable: c:\anaconda3\python.exe
2025-04-10 19:31:08,152:INFO:   machine: Windows-10-10.0.22631-SP0
2025-04-10 19:31:08,152:INFO:PyCaret required dependencies:
2025-04-10 19:31:08,872:INFO:                 pip: 24.0
2025-04-10 19:31:08,872:INFO:          setuptools: 78.1.0
2025-04-10 19:31:08,872:INFO:             pycaret: 3.3.2
2025-04-10 19:31:08,872:INFO:             IPython: 9.1.0
2025-04-10 19:31:08,872:INFO:          ipywidgets: 8.1.6
2025-04-10 19:31:08,872:INFO:                tqdm: 4.67.1
2025-04-10 19:31:08,872:INFO:               numpy: 1.26.4
2025-04-10 19:31:08,872:INFO:              pandas: 2.1.4
2025-04-10 19:31:08,872:INFO:              jinja2: 3.1.6
2025-04-10 19:31:08,872:INFO:               scipy: 1.11.4
2025-04-10 19:31:08,872:INFO:              joblib: 1.3.2
2025-04-10 19:31:08,872:INFO:             sklearn: 1.4.2
2025-04-10 19:31:08,872:INFO:                pyod: 2.0.4
2025-04-10 19:31:08,872:INFO:            imblearn: 0.13.0
2025-04-10 19:31:08,872:INFO:   category_encoders: 2.7.0
2025-04-10 19:31:08,872:INFO:            lightgbm: 4.6.0
2025-04-10 19:31:08,872:INFO:               numba: 0.61.2
2025-04-10 19:31:08,872:INFO:            requests: 2.32.3
2025-04-10 19:31:08,872:INFO:          matplotlib: 3.7.5
2025-04-10 19:31:08,872:INFO:          scikitplot: 0.3.7
2025-04-10 19:31:08,872:INFO:         yellowbrick: 1.5
2025-04-10 19:31:08,872:INFO:              plotly: 5.24.1
2025-04-10 19:31:08,872:INFO:    plotly-resampler: Not installed
2025-04-10 19:31:08,872:INFO:             kaleido: 0.2.1
2025-04-10 19:31:08,872:INFO:           schemdraw: 0.15
2025-04-10 19:31:08,872:INFO:         statsmodels: 0.14.4
2025-04-10 19:31:08,872:INFO:              sktime: 0.26.0
2025-04-10 19:31:08,872:INFO:               tbats: 1.1.3
2025-04-10 19:31:08,872:INFO:            pmdarima: 2.0.4
2025-04-10 19:31:08,872:INFO:              psutil: 7.0.0
2025-04-10 19:31:08,872:INFO:          markupsafe: 3.0.2
2025-04-10 19:31:08,872:INFO:             pickle5: Not installed
2025-04-10 19:31:08,872:INFO:         cloudpickle: 3.1.1
2025-04-10 19:31:08,872:INFO:         deprecation: 2.1.0
2025-04-10 19:31:08,872:INFO:              xxhash: 3.5.0
2025-04-10 19:31:08,872:INFO:           wurlitzer: Not installed
2025-04-10 19:31:08,872:INFO:PyCaret optional dependencies:
2025-04-10 19:31:09,422:INFO:                shap: 0.47.1
2025-04-10 19:31:09,422:INFO:           interpret: Not installed
2025-04-10 19:31:09,422:INFO:                umap: Not installed
2025-04-10 19:31:09,422:INFO:     ydata_profiling: Not installed
2025-04-10 19:31:09,422:INFO:  explainerdashboard: Not installed
2025-04-10 19:31:09,422:INFO:             autoviz: Not installed
2025-04-10 19:31:09,422:INFO:           fairlearn: Not installed
2025-04-10 19:31:09,422:INFO:          deepchecks: Not installed
2025-04-10 19:31:09,422:INFO:             xgboost: Not installed
2025-04-10 19:31:09,422:INFO:            catboost: Not installed
2025-04-10 19:31:09,422:INFO:              kmodes: Not installed
2025-04-10 19:31:09,422:INFO:             mlxtend: Not installed
2025-04-10 19:31:09,422:INFO:       statsforecast: Not installed
2025-04-10 19:31:09,422:INFO:        tune_sklearn: Not installed
2025-04-10 19:31:09,422:INFO:                 ray: Not installed
2025-04-10 19:31:09,422:INFO:            hyperopt: Not installed
2025-04-10 19:31:09,422:INFO:              optuna: Not installed
2025-04-10 19:31:09,422:INFO:               skopt: Not installed
2025-04-10 19:31:09,422:INFO:              mlflow: Not installed
2025-04-10 19:31:09,422:INFO:              gradio: Not installed
2025-04-10 19:31:09,422:INFO:             fastapi: 0.111.0
2025-04-10 19:31:09,422:INFO:             uvicorn: 0.30.0
2025-04-10 19:31:09,422:INFO:              m2cgen: Not installed
2025-04-10 19:31:09,422:INFO:           evidently: Not installed
2025-04-10 19:31:09,422:INFO:               fugue: Not installed
2025-04-10 19:31:09,422:INFO:           streamlit: 1.16.0
2025-04-10 19:31:09,422:INFO:             prophet: Not installed
2025-04-10 19:31:09,422:INFO:None
2025-04-10 19:31:09,422:INFO:Set up data.
2025-04-10 19:31:09,427:INFO:Set up folding strategy.
2025-04-10 19:31:09,427:INFO:Set up train/test split.
2025-04-10 19:31:09,431:INFO:Set up index.
2025-04-10 19:31:09,431:INFO:Assigning column types.
2025-04-10 19:31:09,433:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2025-04-10 19:31:09,455:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-04-10 19:31:09,456:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:31:09,474:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,474:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,495:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-04-10 19:31:09,495:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:31:09,508:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,508:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,508:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2025-04-10 19:31:09,529:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:31:09,542:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,543:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,564:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:31:09,576:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,577:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,577:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2025-04-10 19:31:09,612:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,612:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,647:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,647:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:09,649:INFO:Preparing preprocessing pipeline...
2025-04-10 19:31:09,650:INFO:Set up simple imputation.
2025-04-10 19:31:09,652:INFO:Set up encoding of categorical features.
2025-04-10 19:31:09,652:INFO:Set up removing outliers.
2025-04-10 19:31:09,652:INFO:Set up imbalanced handling.
2025-04-10 19:31:09,792:INFO:Finished creating preprocessing pipeline.
2025-04-10 19:31:09,797:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\JOS~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcceptedCmp1', 'AcceptedCmp2',
                                             'AcceptedCmp3', 'AcceptedCmp4',
                                             'AcceptedCmp5', 'Age', 'Complain',
                                             'Income', 'Kidhome',
                                             'MntFishProducts', 'MntFruits',
                                             'MntGoldProds', 'MntMeatProducts',
                                             'MntSweetProducts', 'MntWines'...
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('remove_outliers',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=RemoveOutliers(method='iforest',
                                                               n_jobs=1,
                                                               random_state=123,
                                                               threshold=0.05))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              random_state=123,
                                                                              sampling_strategy='auto'))))],
         verbose=False)
2025-04-10 19:31:09,797:INFO:Creating final display dataframe.
2025-04-10 19:31:10,503:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target          Response
2                   Target type            Binary
3           Original data shape        (2099, 26)
4        Transformed data shape        (3072, 34)
5   Transformed train set shape        (2442, 34)
6    Transformed test set shape         (630, 34)
7              Numeric features                23
8          Categorical features                 2
9                    Preprocess              True
10              Imputation type            simple
11           Numeric imputation              mean
12       Categorical imputation              mode
13     Maximum one-hot encoding                25
14              Encoding method              None
15              Remove outliers              True
16           Outliers threshold              0.05
17                Fix imbalance              True
18         Fix imbalance method             SMOTE
19               Fold Generator   StratifiedKFold
20                  Fold Number                10
21                     CPU Jobs                -1
22                      Use GPU             False
23               Log Experiment             False
24              Experiment Name  clf-default-name
25                          USI              e00e
2025-04-10 19:31:10,541:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,541:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,577:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,577:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,578:INFO:setup() successfully completed in 2.43s...............
2025-04-10 19:31:10,583:INFO:gpu_param set to False
2025-04-10 19:31:10,616:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,616:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,651:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,652:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:31:10,659:INFO:Initializing compare_models()
2025-04-10 19:31:10,659:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, include=None, exclude=None, fold=None, round=4, cross_validation=True, sort=auc, n_select=1, budget_time=None, turbo=True, errors=raise, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'auc', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'raise', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>})
2025-04-10 19:31:10,659:INFO:Checking exceptions
2025-04-10 19:31:10,663:INFO:Preparing display monitor
2025-04-10 19:31:10,674:INFO:Initializing Logistic Regression
2025-04-10 19:31:10,674:INFO:Total runtime is 0.0 minutes
2025-04-10 19:31:10,676:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:10,676:INFO:Initializing create_model()
2025-04-10 19:31:10,677:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:10,677:INFO:Checking exceptions
2025-04-10 19:31:10,677:INFO:Importing libraries
2025-04-10 19:31:10,677:INFO:Copying training dataset
2025-04-10 19:31:10,681:INFO:Defining folds
2025-04-10 19:31:10,681:INFO:Declaring metric variables
2025-04-10 19:31:10,683:INFO:Importing untrained model
2025-04-10 19:31:10,685:INFO:Logistic Regression Imported successfully
2025-04-10 19:31:10,688:INFO:Starting cross validation
2025-04-10 19:31:10,693:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:14,615:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,664:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,678:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,682:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,690:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,690:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,692:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,705:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,708:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,716:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:31:14,744:INFO:Calculating mean and std
2025-04-10 19:31:14,746:INFO:Creating metrics dataframe
2025-04-10 19:31:14,748:INFO:Uploading results into container
2025-04-10 19:31:14,749:INFO:Uploading model into container now
2025-04-10 19:31:14,749:INFO:_master_model_container: 1
2025-04-10 19:31:14,749:INFO:_display_container: 2
2025-04-10 19:31:14,750:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2025-04-10 19:31:14,750:INFO:create_model() successfully completed......................................
2025-04-10 19:31:14,846:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:14,846:INFO:Creating metrics dataframe
2025-04-10 19:31:14,850:INFO:Initializing K Neighbors Classifier
2025-04-10 19:31:14,850:INFO:Total runtime is 0.06959557135899862 minutes
2025-04-10 19:31:14,852:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:14,852:INFO:Initializing create_model()
2025-04-10 19:31:14,852:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:14,852:INFO:Checking exceptions
2025-04-10 19:31:14,852:INFO:Importing libraries
2025-04-10 19:31:14,852:INFO:Copying training dataset
2025-04-10 19:31:14,856:INFO:Defining folds
2025-04-10 19:31:14,857:INFO:Declaring metric variables
2025-04-10 19:31:14,858:INFO:Importing untrained model
2025-04-10 19:31:14,860:INFO:K Neighbors Classifier Imported successfully
2025-04-10 19:31:14,863:INFO:Starting cross validation
2025-04-10 19:31:14,867:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:18,305:INFO:Calculating mean and std
2025-04-10 19:31:18,306:INFO:Creating metrics dataframe
2025-04-10 19:31:18,308:INFO:Uploading results into container
2025-04-10 19:31:18,309:INFO:Uploading model into container now
2025-04-10 19:31:18,309:INFO:_master_model_container: 2
2025-04-10 19:31:18,309:INFO:_display_container: 2
2025-04-10 19:31:18,310:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2025-04-10 19:31:18,310:INFO:create_model() successfully completed......................................
2025-04-10 19:31:18,402:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:18,402:INFO:Creating metrics dataframe
2025-04-10 19:31:18,406:INFO:Initializing Naive Bayes
2025-04-10 19:31:18,406:INFO:Total runtime is 0.12886101007461548 minutes
2025-04-10 19:31:18,407:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:18,408:INFO:Initializing create_model()
2025-04-10 19:31:18,408:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:18,408:INFO:Checking exceptions
2025-04-10 19:31:18,408:INFO:Importing libraries
2025-04-10 19:31:18,408:INFO:Copying training dataset
2025-04-10 19:31:18,412:INFO:Defining folds
2025-04-10 19:31:18,412:INFO:Declaring metric variables
2025-04-10 19:31:18,414:INFO:Importing untrained model
2025-04-10 19:31:18,416:INFO:Naive Bayes Imported successfully
2025-04-10 19:31:18,419:INFO:Starting cross validation
2025-04-10 19:31:18,424:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:18,619:INFO:Calculating mean and std
2025-04-10 19:31:18,619:INFO:Creating metrics dataframe
2025-04-10 19:31:18,620:INFO:Uploading results into container
2025-04-10 19:31:18,621:INFO:Uploading model into container now
2025-04-10 19:31:18,621:INFO:_master_model_container: 3
2025-04-10 19:31:18,621:INFO:_display_container: 2
2025-04-10 19:31:18,621:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2025-04-10 19:31:18,621:INFO:create_model() successfully completed......................................
2025-04-10 19:31:18,708:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:18,708:INFO:Creating metrics dataframe
2025-04-10 19:31:18,712:INFO:Initializing Decision Tree Classifier
2025-04-10 19:31:18,712:INFO:Total runtime is 0.13395620584487916 minutes
2025-04-10 19:31:18,714:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:18,715:INFO:Initializing create_model()
2025-04-10 19:31:18,715:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:18,715:INFO:Checking exceptions
2025-04-10 19:31:18,715:INFO:Importing libraries
2025-04-10 19:31:18,715:INFO:Copying training dataset
2025-04-10 19:31:18,718:INFO:Defining folds
2025-04-10 19:31:18,718:INFO:Declaring metric variables
2025-04-10 19:31:18,720:INFO:Importing untrained model
2025-04-10 19:31:18,722:INFO:Decision Tree Classifier Imported successfully
2025-04-10 19:31:18,726:INFO:Starting cross validation
2025-04-10 19:31:18,730:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:18,947:INFO:Calculating mean and std
2025-04-10 19:31:18,947:INFO:Creating metrics dataframe
2025-04-10 19:31:18,948:INFO:Uploading results into container
2025-04-10 19:31:18,949:INFO:Uploading model into container now
2025-04-10 19:31:18,949:INFO:_master_model_container: 4
2025-04-10 19:31:18,949:INFO:_display_container: 2
2025-04-10 19:31:18,949:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=123, splitter='best')
2025-04-10 19:31:18,949:INFO:create_model() successfully completed......................................
2025-04-10 19:31:19,033:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:19,033:INFO:Creating metrics dataframe
2025-04-10 19:31:19,037:INFO:Initializing SVM - Linear Kernel
2025-04-10 19:31:19,037:INFO:Total runtime is 0.1393800139427185 minutes
2025-04-10 19:31:19,039:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:19,039:INFO:Initializing create_model()
2025-04-10 19:31:19,039:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:19,039:INFO:Checking exceptions
2025-04-10 19:31:19,039:INFO:Importing libraries
2025-04-10 19:31:19,039:INFO:Copying training dataset
2025-04-10 19:31:19,043:INFO:Defining folds
2025-04-10 19:31:19,043:INFO:Declaring metric variables
2025-04-10 19:31:19,045:INFO:Importing untrained model
2025-04-10 19:31:19,046:INFO:SVM - Linear Kernel Imported successfully
2025-04-10 19:31:19,049:INFO:Starting cross validation
2025-04-10 19:31:19,055:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:19,243:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:19,260:INFO:Calculating mean and std
2025-04-10 19:31:19,261:INFO:Creating metrics dataframe
2025-04-10 19:31:19,262:INFO:Uploading results into container
2025-04-10 19:31:19,262:INFO:Uploading model into container now
2025-04-10 19:31:19,262:INFO:_master_model_container: 5
2025-04-10 19:31:19,262:INFO:_display_container: 2
2025-04-10 19:31:19,263:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2025-04-10 19:31:19,263:INFO:create_model() successfully completed......................................
2025-04-10 19:31:19,351:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:19,351:INFO:Creating metrics dataframe
2025-04-10 19:31:19,356:INFO:Initializing Ridge Classifier
2025-04-10 19:31:19,356:INFO:Total runtime is 0.14469138383865357 minutes
2025-04-10 19:31:19,357:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:19,358:INFO:Initializing create_model()
2025-04-10 19:31:19,358:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:19,358:INFO:Checking exceptions
2025-04-10 19:31:19,358:INFO:Importing libraries
2025-04-10 19:31:19,358:INFO:Copying training dataset
2025-04-10 19:31:19,362:INFO:Defining folds
2025-04-10 19:31:19,362:INFO:Declaring metric variables
2025-04-10 19:31:19,364:INFO:Importing untrained model
2025-04-10 19:31:19,366:INFO:Ridge Classifier Imported successfully
2025-04-10 19:31:19,369:INFO:Starting cross validation
2025-04-10 19:31:19,374:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:19,558:INFO:Calculating mean and std
2025-04-10 19:31:19,558:INFO:Creating metrics dataframe
2025-04-10 19:31:19,559:INFO:Uploading results into container
2025-04-10 19:31:19,560:INFO:Uploading model into container now
2025-04-10 19:31:19,560:INFO:_master_model_container: 6
2025-04-10 19:31:19,560:INFO:_display_container: 2
2025-04-10 19:31:19,560:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2025-04-10 19:31:19,560:INFO:create_model() successfully completed......................................
2025-04-10 19:31:19,642:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:19,642:INFO:Creating metrics dataframe
2025-04-10 19:31:19,646:INFO:Initializing Random Forest Classifier
2025-04-10 19:31:19,647:INFO:Total runtime is 0.14954642454783124 minutes
2025-04-10 19:31:19,648:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:19,648:INFO:Initializing create_model()
2025-04-10 19:31:19,648:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:19,649:INFO:Checking exceptions
2025-04-10 19:31:19,649:INFO:Importing libraries
2025-04-10 19:31:19,649:INFO:Copying training dataset
2025-04-10 19:31:19,653:INFO:Defining folds
2025-04-10 19:31:19,653:INFO:Declaring metric variables
2025-04-10 19:31:19,655:INFO:Importing untrained model
2025-04-10 19:31:19,656:INFO:Random Forest Classifier Imported successfully
2025-04-10 19:31:19,660:INFO:Starting cross validation
2025-04-10 19:31:19,664:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:20,163:INFO:Calculating mean and std
2025-04-10 19:31:20,163:INFO:Creating metrics dataframe
2025-04-10 19:31:20,164:INFO:Uploading results into container
2025-04-10 19:31:20,165:INFO:Uploading model into container now
2025-04-10 19:31:20,165:INFO:_master_model_container: 7
2025-04-10 19:31:20,165:INFO:_display_container: 2
2025-04-10 19:31:20,165:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=123, verbose=0,
                       warm_start=False)
2025-04-10 19:31:20,165:INFO:create_model() successfully completed......................................
2025-04-10 19:31:20,252:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:20,252:INFO:Creating metrics dataframe
2025-04-10 19:31:20,257:INFO:Initializing Quadratic Discriminant Analysis
2025-04-10 19:31:20,257:INFO:Total runtime is 0.15971418619155886 minutes
2025-04-10 19:31:20,259:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:20,260:INFO:Initializing create_model()
2025-04-10 19:31:20,260:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:20,260:INFO:Checking exceptions
2025-04-10 19:31:20,260:INFO:Importing libraries
2025-04-10 19:31:20,260:INFO:Copying training dataset
2025-04-10 19:31:20,264:INFO:Defining folds
2025-04-10 19:31:20,264:INFO:Declaring metric variables
2025-04-10 19:31:20,265:INFO:Importing untrained model
2025-04-10 19:31:20,267:INFO:Quadratic Discriminant Analysis Imported successfully
2025-04-10 19:31:20,271:INFO:Starting cross validation
2025-04-10 19:31:20,275:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:20,407:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,409:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,412:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,415:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,419:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,419:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,433:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,434:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,444:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,449:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:31:20,469:INFO:Calculating mean and std
2025-04-10 19:31:20,469:INFO:Creating metrics dataframe
2025-04-10 19:31:20,471:INFO:Uploading results into container
2025-04-10 19:31:20,471:INFO:Uploading model into container now
2025-04-10 19:31:20,471:INFO:_master_model_container: 8
2025-04-10 19:31:20,471:INFO:_display_container: 2
2025-04-10 19:31:20,471:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2025-04-10 19:31:20,471:INFO:create_model() successfully completed......................................
2025-04-10 19:31:20,554:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:20,554:INFO:Creating metrics dataframe
2025-04-10 19:31:20,558:INFO:Initializing Ada Boost Classifier
2025-04-10 19:31:20,559:INFO:Total runtime is 0.1647379557291667 minutes
2025-04-10 19:31:20,560:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:20,560:INFO:Initializing create_model()
2025-04-10 19:31:20,560:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:20,561:INFO:Checking exceptions
2025-04-10 19:31:20,561:INFO:Importing libraries
2025-04-10 19:31:20,561:INFO:Copying training dataset
2025-04-10 19:31:20,564:INFO:Defining folds
2025-04-10 19:31:20,564:INFO:Declaring metric variables
2025-04-10 19:31:20,566:INFO:Importing untrained model
2025-04-10 19:31:20,567:INFO:Ada Boost Classifier Imported successfully
2025-04-10 19:31:20,572:INFO:Starting cross validation
2025-04-10 19:31:20,576:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:20,705:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,707:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,708:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,722:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,722:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,730:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,730:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,732:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,747:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,749:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:31:20,981:INFO:Calculating mean and std
2025-04-10 19:31:20,981:INFO:Creating metrics dataframe
2025-04-10 19:31:20,982:INFO:Uploading results into container
2025-04-10 19:31:20,983:INFO:Uploading model into container now
2025-04-10 19:31:20,983:INFO:_master_model_container: 9
2025-04-10 19:31:20,983:INFO:_display_container: 2
2025-04-10 19:31:20,983:INFO:AdaBoostClassifier(algorithm='SAMME.R', estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=123)
2025-04-10 19:31:20,983:INFO:create_model() successfully completed......................................
2025-04-10 19:31:21,068:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:21,068:INFO:Creating metrics dataframe
2025-04-10 19:31:21,073:INFO:Initializing Gradient Boosting Classifier
2025-04-10 19:31:21,073:INFO:Total runtime is 0.17331221103668215 minutes
2025-04-10 19:31:21,075:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:21,075:INFO:Initializing create_model()
2025-04-10 19:31:21,075:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:21,075:INFO:Checking exceptions
2025-04-10 19:31:21,075:INFO:Importing libraries
2025-04-10 19:31:21,075:INFO:Copying training dataset
2025-04-10 19:31:21,079:INFO:Defining folds
2025-04-10 19:31:21,079:INFO:Declaring metric variables
2025-04-10 19:31:21,080:INFO:Importing untrained model
2025-04-10 19:31:21,082:INFO:Gradient Boosting Classifier Imported successfully
2025-04-10 19:31:21,086:INFO:Starting cross validation
2025-04-10 19:31:21,090:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:22,055:INFO:Calculating mean and std
2025-04-10 19:31:22,055:INFO:Creating metrics dataframe
2025-04-10 19:31:22,056:INFO:Uploading results into container
2025-04-10 19:31:22,056:INFO:Uploading model into container now
2025-04-10 19:31:22,057:INFO:_master_model_container: 10
2025-04-10 19:31:22,057:INFO:_display_container: 2
2025-04-10 19:31:22,057:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2025-04-10 19:31:22,057:INFO:create_model() successfully completed......................................
2025-04-10 19:31:22,148:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:22,149:INFO:Creating metrics dataframe
2025-04-10 19:31:22,154:INFO:Initializing Linear Discriminant Analysis
2025-04-10 19:31:22,154:INFO:Total runtime is 0.1913251320521037 minutes
2025-04-10 19:31:22,158:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:22,158:INFO:Initializing create_model()
2025-04-10 19:31:22,158:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:22,158:INFO:Checking exceptions
2025-04-10 19:31:22,158:INFO:Importing libraries
2025-04-10 19:31:22,158:INFO:Copying training dataset
2025-04-10 19:31:22,162:INFO:Defining folds
2025-04-10 19:31:22,162:INFO:Declaring metric variables
2025-04-10 19:31:22,164:INFO:Importing untrained model
2025-04-10 19:31:22,165:INFO:Linear Discriminant Analysis Imported successfully
2025-04-10 19:31:22,169:INFO:Starting cross validation
2025-04-10 19:31:22,173:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:22,358:INFO:Calculating mean and std
2025-04-10 19:31:22,358:INFO:Creating metrics dataframe
2025-04-10 19:31:22,359:INFO:Uploading results into container
2025-04-10 19:31:22,360:INFO:Uploading model into container now
2025-04-10 19:31:22,360:INFO:_master_model_container: 11
2025-04-10 19:31:22,360:INFO:_display_container: 2
2025-04-10 19:31:22,360:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2025-04-10 19:31:22,361:INFO:create_model() successfully completed......................................
2025-04-10 19:31:22,443:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:22,443:INFO:Creating metrics dataframe
2025-04-10 19:31:22,447:INFO:Initializing Extra Trees Classifier
2025-04-10 19:31:22,447:INFO:Total runtime is 0.196216889222463 minutes
2025-04-10 19:31:22,449:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:22,449:INFO:Initializing create_model()
2025-04-10 19:31:22,449:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:22,450:INFO:Checking exceptions
2025-04-10 19:31:22,450:INFO:Importing libraries
2025-04-10 19:31:22,450:INFO:Copying training dataset
2025-04-10 19:31:22,454:INFO:Defining folds
2025-04-10 19:31:22,454:INFO:Declaring metric variables
2025-04-10 19:31:22,455:INFO:Importing untrained model
2025-04-10 19:31:22,457:INFO:Extra Trees Classifier Imported successfully
2025-04-10 19:31:22,460:INFO:Starting cross validation
2025-04-10 19:31:22,465:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:22,834:INFO:Calculating mean and std
2025-04-10 19:31:22,834:INFO:Creating metrics dataframe
2025-04-10 19:31:22,835:INFO:Uploading results into container
2025-04-10 19:31:22,835:INFO:Uploading model into container now
2025-04-10 19:31:22,836:INFO:_master_model_container: 12
2025-04-10 19:31:22,836:INFO:_display_container: 2
2025-04-10 19:31:22,836:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=123, verbose=0,
                     warm_start=False)
2025-04-10 19:31:22,836:INFO:create_model() successfully completed......................................
2025-04-10 19:31:22,919:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:22,919:INFO:Creating metrics dataframe
2025-04-10 19:31:22,924:INFO:Initializing Light Gradient Boosting Machine
2025-04-10 19:31:22,924:INFO:Total runtime is 0.2041555484135946 minutes
2025-04-10 19:31:22,926:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:22,926:INFO:Initializing create_model()
2025-04-10 19:31:22,926:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:22,926:INFO:Checking exceptions
2025-04-10 19:31:22,926:INFO:Importing libraries
2025-04-10 19:31:22,927:INFO:Copying training dataset
2025-04-10 19:31:22,930:INFO:Defining folds
2025-04-10 19:31:22,930:INFO:Declaring metric variables
2025-04-10 19:31:22,932:INFO:Importing untrained model
2025-04-10 19:31:22,934:INFO:Light Gradient Boosting Machine Imported successfully
2025-04-10 19:31:22,937:INFO:Starting cross validation
2025-04-10 19:31:22,942:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:24,206:INFO:Calculating mean and std
2025-04-10 19:31:24,207:INFO:Creating metrics dataframe
2025-04-10 19:31:24,208:INFO:Uploading results into container
2025-04-10 19:31:24,208:INFO:Uploading model into container now
2025-04-10 19:31:24,209:INFO:_master_model_container: 13
2025-04-10 19:31:24,209:INFO:_display_container: 2
2025-04-10 19:31:24,209:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2025-04-10 19:31:24,209:INFO:create_model() successfully completed......................................
2025-04-10 19:31:24,299:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:24,299:INFO:Creating metrics dataframe
2025-04-10 19:31:24,304:INFO:Initializing Dummy Classifier
2025-04-10 19:31:24,304:INFO:Total runtime is 0.227166231473287 minutes
2025-04-10 19:31:24,306:INFO:SubProcess create_model() called ==================================
2025-04-10 19:31:24,306:INFO:Initializing create_model()
2025-04-10 19:31:24,306:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB34190750>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:31:24,306:INFO:Checking exceptions
2025-04-10 19:31:24,306:INFO:Importing libraries
2025-04-10 19:31:24,306:INFO:Copying training dataset
2025-04-10 19:31:24,310:INFO:Defining folds
2025-04-10 19:31:24,310:INFO:Declaring metric variables
2025-04-10 19:31:24,312:INFO:Importing untrained model
2025-04-10 19:31:24,314:INFO:Dummy Classifier Imported successfully
2025-04-10 19:31:24,317:INFO:Starting cross validation
2025-04-10 19:31:24,322:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:31:24,442:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,445:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,459:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,462:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,464:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,466:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,468:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,472:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,475:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,478:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,480:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,483:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,484:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,484:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,485:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,486:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,487:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,488:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,495:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (146, 2) instead.

  warnings.warn(

2025-04-10 19:31:24,499:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:31:24,508:INFO:Calculating mean and std
2025-04-10 19:31:24,508:INFO:Creating metrics dataframe
2025-04-10 19:31:24,510:INFO:Uploading results into container
2025-04-10 19:31:24,510:INFO:Uploading model into container now
2025-04-10 19:31:24,510:INFO:_master_model_container: 14
2025-04-10 19:31:24,510:INFO:_display_container: 2
2025-04-10 19:31:24,510:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2025-04-10 19:31:24,510:INFO:create_model() successfully completed......................................
2025-04-10 19:31:24,594:INFO:SubProcess create_model() end ==================================
2025-04-10 19:31:24,594:INFO:Creating metrics dataframe
2025-04-10 19:31:24,604:INFO:Initializing create_model()
2025-04-10 19:31:24,604:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31964A50>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-04-10 19:31:24,604:INFO:Checking exceptions
2025-04-10 19:31:24,605:INFO:Importing libraries
2025-04-10 19:31:24,605:INFO:Copying training dataset
2025-04-10 19:31:24,609:INFO:Defining folds
2025-04-10 19:31:24,609:INFO:Declaring metric variables
2025-04-10 19:31:24,609:INFO:Importing untrained model
2025-04-10 19:31:24,609:INFO:Declaring custom model
2025-04-10 19:31:24,609:INFO:Ridge Classifier Imported successfully
2025-04-10 19:31:24,613:INFO:Cross validation set to False
2025-04-10 19:31:24,613:INFO:Fitting Model
2025-04-10 19:31:24,729:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2025-04-10 19:31:24,729:INFO:create_model() successfully completed......................................
2025-04-10 19:31:24,828:INFO:_master_model_container: 14
2025-04-10 19:31:24,828:INFO:_display_container: 2
2025-04-10 19:31:24,828:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2025-04-10 19:31:24,828:INFO:compare_models() successfully completed......................................
2025-04-10 19:37:44,633:INFO:PyCaret ClassificationExperiment
2025-04-10 19:37:44,633:INFO:Logging name: clf-default-name
2025-04-10 19:37:44,633:INFO:ML Usecase: MLUsecase.CLASSIFICATION
2025-04-10 19:37:44,633:INFO:version 3.3.2
2025-04-10 19:37:44,633:INFO:Initializing setup()
2025-04-10 19:37:44,633:INFO:self.USI: 15fa
2025-04-10 19:37:44,633:INFO:self._variable_keys: {'pipeline', 'X_train', 'y_test', 'fold_groups_param', 'is_multiclass', 'html_param', 'y_train', 'fix_imbalance', 'fold_shuffle_param', 'exp_name_log', 'fold_generator', 'data', 'target_param', 'gpu_n_jobs_param', 'logging_param', 'idx', 'log_plots_param', 'X_test', 'y', 'seed', 'gpu_param', 'X', '_available_plots', 'USI', 'n_jobs_param', '_ml_usecase', 'memory', 'exp_id'}
2025-04-10 19:37:44,633:INFO:Checking environment
2025-04-10 19:37:44,633:INFO:python_version: 3.11.7
2025-04-10 19:37:44,633:INFO:python_build: ('main', 'Dec 15 2023 18:05:47')
2025-04-10 19:37:44,633:INFO:machine: AMD64
2025-04-10 19:37:44,633:INFO:platform: Windows-10-10.0.22631-SP0
2025-04-10 19:37:44,637:INFO:Memory: svmem(total=34111008768, available=15885512704, percent=53.4, used=18225496064, free=15885512704)
2025-04-10 19:37:44,638:INFO:Physical Core: 14
2025-04-10 19:37:44,638:INFO:Logical Core: 20
2025-04-10 19:37:44,638:INFO:Checking libraries
2025-04-10 19:37:44,638:INFO:System:
2025-04-10 19:37:44,638:INFO:    python: 3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]
2025-04-10 19:37:44,638:INFO:executable: c:\anaconda3\python.exe
2025-04-10 19:37:44,638:INFO:   machine: Windows-10-10.0.22631-SP0
2025-04-10 19:37:44,638:INFO:PyCaret required dependencies:
2025-04-10 19:37:44,638:INFO:                 pip: 24.0
2025-04-10 19:37:44,638:INFO:          setuptools: 78.1.0
2025-04-10 19:37:44,638:INFO:             pycaret: 3.3.2
2025-04-10 19:37:44,638:INFO:             IPython: 9.1.0
2025-04-10 19:37:44,638:INFO:          ipywidgets: 8.1.6
2025-04-10 19:37:44,638:INFO:                tqdm: 4.67.1
2025-04-10 19:37:44,638:INFO:               numpy: 1.26.4
2025-04-10 19:37:44,638:INFO:              pandas: 2.1.4
2025-04-10 19:37:44,638:INFO:              jinja2: 3.1.6
2025-04-10 19:37:44,638:INFO:               scipy: 1.11.4
2025-04-10 19:37:44,638:INFO:              joblib: 1.3.2
2025-04-10 19:37:44,638:INFO:             sklearn: 1.4.2
2025-04-10 19:37:44,638:INFO:                pyod: 2.0.4
2025-04-10 19:37:44,638:INFO:            imblearn: 0.13.0
2025-04-10 19:37:44,638:INFO:   category_encoders: 2.7.0
2025-04-10 19:37:44,638:INFO:            lightgbm: 4.6.0
2025-04-10 19:37:44,638:INFO:               numba: 0.61.2
2025-04-10 19:37:44,638:INFO:            requests: 2.32.3
2025-04-10 19:37:44,638:INFO:          matplotlib: 3.7.5
2025-04-10 19:37:44,638:INFO:          scikitplot: 0.3.7
2025-04-10 19:37:44,638:INFO:         yellowbrick: 1.5
2025-04-10 19:37:44,638:INFO:              plotly: 5.24.1
2025-04-10 19:37:44,638:INFO:    plotly-resampler: Not installed
2025-04-10 19:37:44,638:INFO:             kaleido: 0.2.1
2025-04-10 19:37:44,638:INFO:           schemdraw: 0.15
2025-04-10 19:37:44,638:INFO:         statsmodels: 0.14.4
2025-04-10 19:37:44,638:INFO:              sktime: 0.26.0
2025-04-10 19:37:44,638:INFO:               tbats: 1.1.3
2025-04-10 19:37:44,638:INFO:            pmdarima: 2.0.4
2025-04-10 19:37:44,638:INFO:              psutil: 7.0.0
2025-04-10 19:37:44,638:INFO:          markupsafe: 3.0.2
2025-04-10 19:37:44,638:INFO:             pickle5: Not installed
2025-04-10 19:37:44,638:INFO:         cloudpickle: 3.1.1
2025-04-10 19:37:44,638:INFO:         deprecation: 2.1.0
2025-04-10 19:37:44,638:INFO:              xxhash: 3.5.0
2025-04-10 19:37:44,638:INFO:           wurlitzer: Not installed
2025-04-10 19:37:44,638:INFO:PyCaret optional dependencies:
2025-04-10 19:37:44,638:INFO:                shap: 0.47.1
2025-04-10 19:37:44,638:INFO:           interpret: Not installed
2025-04-10 19:37:44,638:INFO:                umap: Not installed
2025-04-10 19:37:44,638:INFO:     ydata_profiling: Not installed
2025-04-10 19:37:44,639:INFO:  explainerdashboard: Not installed
2025-04-10 19:37:44,639:INFO:             autoviz: Not installed
2025-04-10 19:37:44,639:INFO:           fairlearn: Not installed
2025-04-10 19:37:44,639:INFO:          deepchecks: Not installed
2025-04-10 19:37:44,639:INFO:             xgboost: Not installed
2025-04-10 19:37:44,639:INFO:            catboost: Not installed
2025-04-10 19:37:44,639:INFO:              kmodes: Not installed
2025-04-10 19:37:44,639:INFO:             mlxtend: Not installed
2025-04-10 19:37:44,639:INFO:       statsforecast: Not installed
2025-04-10 19:37:44,639:INFO:        tune_sklearn: Not installed
2025-04-10 19:37:44,639:INFO:                 ray: Not installed
2025-04-10 19:37:44,639:INFO:            hyperopt: Not installed
2025-04-10 19:37:44,639:INFO:              optuna: Not installed
2025-04-10 19:37:44,639:INFO:               skopt: Not installed
2025-04-10 19:37:44,639:INFO:              mlflow: Not installed
2025-04-10 19:37:44,639:INFO:              gradio: Not installed
2025-04-10 19:37:44,639:INFO:             fastapi: 0.111.0
2025-04-10 19:37:44,639:INFO:             uvicorn: 0.30.0
2025-04-10 19:37:44,639:INFO:              m2cgen: Not installed
2025-04-10 19:37:44,639:INFO:           evidently: Not installed
2025-04-10 19:37:44,639:INFO:               fugue: Not installed
2025-04-10 19:37:44,639:INFO:           streamlit: 1.16.0
2025-04-10 19:37:44,639:INFO:             prophet: Not installed
2025-04-10 19:37:44,639:INFO:None
2025-04-10 19:37:44,639:INFO:Set up data.
2025-04-10 19:37:44,643:INFO:Set up folding strategy.
2025-04-10 19:37:44,643:INFO:Set up train/test split.
2025-04-10 19:37:44,647:INFO:Set up index.
2025-04-10 19:37:44,647:INFO:Assigning column types.
2025-04-10 19:37:44,649:INFO:Engine successfully changes for model 'lr' to 'sklearn'.
2025-04-10 19:37:44,669:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-04-10 19:37:44,670:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:37:44,683:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,683:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,703:INFO:Engine for model 'knn' has not been set explicitly, hence returning None.
2025-04-10 19:37:44,704:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:37:44,716:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,716:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,716:INFO:Engine successfully changes for model 'knn' to 'sklearn'.
2025-04-10 19:37:44,737:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:37:44,750:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,750:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,770:INFO:Engine for model 'rbfsvm' has not been set explicitly, hence returning None.
2025-04-10 19:37:44,783:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,784:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,784:INFO:Engine successfully changes for model 'rbfsvm' to 'sklearn'.
2025-04-10 19:37:44,817:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,817:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,851:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,851:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:44,852:INFO:Preparing preprocessing pipeline...
2025-04-10 19:37:44,853:INFO:Set up simple imputation.
2025-04-10 19:37:44,855:INFO:Set up encoding of categorical features.
2025-04-10 19:37:44,855:INFO:Set up removing outliers.
2025-04-10 19:37:44,855:INFO:Set up imbalanced handling.
2025-04-10 19:37:44,979:INFO:Finished creating preprocessing pipeline.
2025-04-10 19:37:44,983:INFO:Pipeline: Pipeline(memory=FastMemory(location=C:\Users\JOS~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcceptedCmp1', 'AcceptedCmp2',
                                             'AcceptedCmp3', 'AcceptedCmp4',
                                             'AcceptedCmp5', 'Age', 'Complain',
                                             'Income', 'Kidhome',
                                             'MntFishProducts', 'MntFruits',
                                             'MntGoldProds', 'MntMeatProducts',
                                             'MntSweetProducts', 'MntWines'...
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('remove_outliers',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=RemoveOutliers(method='iforest',
                                                               n_jobs=1,
                                                               random_state=123,
                                                               threshold=0.05))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              random_state=123,
                                                                              sampling_strategy='auto'))))],
         verbose=False)
2025-04-10 19:37:44,983:INFO:Creating final display dataframe.
2025-04-10 19:37:45,171:INFO:Setup _display_container:                     Description             Value
0                    Session id               123
1                        Target          Response
2                   Target type            Binary
3           Original data shape        (2099, 26)
4        Transformed data shape        (3072, 34)
5   Transformed train set shape        (2442, 34)
6    Transformed test set shape         (630, 34)
7              Numeric features                23
8          Categorical features                 2
9                    Preprocess              True
10              Imputation type            simple
11           Numeric imputation              mean
12       Categorical imputation              mode
13     Maximum one-hot encoding                25
14              Encoding method              None
15              Remove outliers              True
16           Outliers threshold              0.05
17                Fix imbalance              True
18         Fix imbalance method             SMOTE
19               Fold Generator   StratifiedKFold
20                  Fold Number                10
21                     CPU Jobs                -1
22                      Use GPU             False
23               Log Experiment             False
24              Experiment Name  clf-default-name
25                          USI              15fa
2025-04-10 19:37:45,210:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:45,210:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:45,244:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:45,244:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:45,245:INFO:setup() successfully completed in 0.61s...............
2025-04-10 19:37:49,256:INFO:gpu_param set to False
2025-04-10 19:37:49,296:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:49,297:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:49,329:WARNING:
'xgboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install xgboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:49,329:WARNING:
'catboost' is a soft dependency and not included in the pycaret installation. Please run: `pip install catboost` to install.
Alternately, you can install this by running `pip install pycaret[models]`
2025-04-10 19:37:57,582:INFO:Initializing compare_models()
2025-04-10 19:37:57,582:INFO:compare_models(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, include=None, exclude=None, fold=None, round=4, cross_validation=True, sort=auc, n_select=1, budget_time=None, turbo=True, errors=raise, fit_kwargs=None, groups=None, experiment_custom_tags=None, probability_threshold=None, verbose=True, parallel=None, caller_params={'self': <pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, 'include': None, 'exclude': None, 'fold': None, 'round': 4, 'cross_validation': True, 'sort': 'auc', 'n_select': 1, 'budget_time': None, 'turbo': True, 'errors': 'raise', 'fit_kwargs': None, 'groups': None, 'experiment_custom_tags': None, 'probability_threshold': None, 'engine': None, 'verbose': True, 'parallel': None, '__class__': <class 'pycaret.classification.oop.ClassificationExperiment'>})
2025-04-10 19:37:57,582:INFO:Checking exceptions
2025-04-10 19:37:57,585:INFO:Preparing display monitor
2025-04-10 19:37:57,598:INFO:Initializing Logistic Regression
2025-04-10 19:37:57,598:INFO:Total runtime is 0.0 minutes
2025-04-10 19:37:57,601:INFO:SubProcess create_model() called ==================================
2025-04-10 19:37:57,601:INFO:Initializing create_model()
2025-04-10 19:37:57,601:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=lr, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:37:57,601:INFO:Checking exceptions
2025-04-10 19:37:57,601:INFO:Importing libraries
2025-04-10 19:37:57,601:INFO:Copying training dataset
2025-04-10 19:37:57,609:INFO:Defining folds
2025-04-10 19:37:57,610:INFO:Declaring metric variables
2025-04-10 19:37:57,612:INFO:Importing untrained model
2025-04-10 19:37:57,615:INFO:Logistic Regression Imported successfully
2025-04-10 19:37:57,623:INFO:Starting cross validation
2025-04-10 19:37:57,629:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:01,701:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,721:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,738:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,739:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,739:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,740:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,767:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,781:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,783:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,808:WARNING:c:\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

2025-04-10 19:38:01,837:INFO:Calculating mean and std
2025-04-10 19:38:01,838:INFO:Creating metrics dataframe
2025-04-10 19:38:01,840:INFO:Uploading results into container
2025-04-10 19:38:01,840:INFO:Uploading model into container now
2025-04-10 19:38:01,841:INFO:_master_model_container: 1
2025-04-10 19:38:01,841:INFO:_display_container: 2
2025-04-10 19:38:01,841:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2025-04-10 19:38:01,841:INFO:create_model() successfully completed......................................
2025-04-10 19:38:01,932:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:01,932:INFO:Creating metrics dataframe
2025-04-10 19:38:01,936:INFO:Initializing K Neighbors Classifier
2025-04-10 19:38:01,936:INFO:Total runtime is 0.07230261564254761 minutes
2025-04-10 19:38:01,938:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:01,938:INFO:Initializing create_model()
2025-04-10 19:38:01,938:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=knn, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:01,938:INFO:Checking exceptions
2025-04-10 19:38:01,938:INFO:Importing libraries
2025-04-10 19:38:01,939:INFO:Copying training dataset
2025-04-10 19:38:01,943:INFO:Defining folds
2025-04-10 19:38:01,943:INFO:Declaring metric variables
2025-04-10 19:38:01,944:INFO:Importing untrained model
2025-04-10 19:38:01,946:INFO:K Neighbors Classifier Imported successfully
2025-04-10 19:38:01,950:INFO:Starting cross validation
2025-04-10 19:38:01,956:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:05,313:INFO:Calculating mean and std
2025-04-10 19:38:05,313:INFO:Creating metrics dataframe
2025-04-10 19:38:05,315:INFO:Uploading results into container
2025-04-10 19:38:05,315:INFO:Uploading model into container now
2025-04-10 19:38:05,315:INFO:_master_model_container: 2
2025-04-10 19:38:05,315:INFO:_display_container: 2
2025-04-10 19:38:05,316:INFO:KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                     weights='uniform')
2025-04-10 19:38:05,316:INFO:create_model() successfully completed......................................
2025-04-10 19:38:05,401:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:05,401:INFO:Creating metrics dataframe
2025-04-10 19:38:05,404:INFO:Initializing Naive Bayes
2025-04-10 19:38:05,404:INFO:Total runtime is 0.13010453383127848 minutes
2025-04-10 19:38:05,406:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:05,406:INFO:Initializing create_model()
2025-04-10 19:38:05,406:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=nb, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:05,406:INFO:Checking exceptions
2025-04-10 19:38:05,406:INFO:Importing libraries
2025-04-10 19:38:05,406:INFO:Copying training dataset
2025-04-10 19:38:05,410:INFO:Defining folds
2025-04-10 19:38:05,410:INFO:Declaring metric variables
2025-04-10 19:38:05,412:INFO:Importing untrained model
2025-04-10 19:38:05,413:INFO:Naive Bayes Imported successfully
2025-04-10 19:38:05,418:INFO:Starting cross validation
2025-04-10 19:38:05,423:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:05,618:INFO:Calculating mean and std
2025-04-10 19:38:05,618:INFO:Creating metrics dataframe
2025-04-10 19:38:05,620:INFO:Uploading results into container
2025-04-10 19:38:05,620:INFO:Uploading model into container now
2025-04-10 19:38:05,620:INFO:_master_model_container: 3
2025-04-10 19:38:05,620:INFO:_display_container: 2
2025-04-10 19:38:05,620:INFO:GaussianNB(priors=None, var_smoothing=1e-09)
2025-04-10 19:38:05,620:INFO:create_model() successfully completed......................................
2025-04-10 19:38:05,710:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:05,710:INFO:Creating metrics dataframe
2025-04-10 19:38:05,714:INFO:Initializing Decision Tree Classifier
2025-04-10 19:38:05,714:INFO:Total runtime is 0.13525729179382323 minutes
2025-04-10 19:38:05,717:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:05,717:INFO:Initializing create_model()
2025-04-10 19:38:05,717:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=dt, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:05,717:INFO:Checking exceptions
2025-04-10 19:38:05,717:INFO:Importing libraries
2025-04-10 19:38:05,717:INFO:Copying training dataset
2025-04-10 19:38:05,721:INFO:Defining folds
2025-04-10 19:38:05,721:INFO:Declaring metric variables
2025-04-10 19:38:05,723:INFO:Importing untrained model
2025-04-10 19:38:05,724:INFO:Decision Tree Classifier Imported successfully
2025-04-10 19:38:05,728:INFO:Starting cross validation
2025-04-10 19:38:05,733:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:05,931:INFO:Calculating mean and std
2025-04-10 19:38:05,931:INFO:Creating metrics dataframe
2025-04-10 19:38:05,933:INFO:Uploading results into container
2025-04-10 19:38:05,934:INFO:Uploading model into container now
2025-04-10 19:38:05,934:INFO:_master_model_container: 4
2025-04-10 19:38:05,934:INFO:_display_container: 2
2025-04-10 19:38:05,934:INFO:DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, random_state=123, splitter='best')
2025-04-10 19:38:05,934:INFO:create_model() successfully completed......................................
2025-04-10 19:38:06,018:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:06,018:INFO:Creating metrics dataframe
2025-04-10 19:38:06,022:INFO:Initializing SVM - Linear Kernel
2025-04-10 19:38:06,022:INFO:Total runtime is 0.1404030998547872 minutes
2025-04-10 19:38:06,024:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:06,024:INFO:Initializing create_model()
2025-04-10 19:38:06,024:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=svm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:06,024:INFO:Checking exceptions
2025-04-10 19:38:06,025:INFO:Importing libraries
2025-04-10 19:38:06,025:INFO:Copying training dataset
2025-04-10 19:38:06,028:INFO:Defining folds
2025-04-10 19:38:06,028:INFO:Declaring metric variables
2025-04-10 19:38:06,030:INFO:Importing untrained model
2025-04-10 19:38:06,031:INFO:SVM - Linear Kernel Imported successfully
2025-04-10 19:38:06,034:INFO:Starting cross validation
2025-04-10 19:38:06,039:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:06,235:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:06,246:INFO:Calculating mean and std
2025-04-10 19:38:06,246:INFO:Creating metrics dataframe
2025-04-10 19:38:06,248:INFO:Uploading results into container
2025-04-10 19:38:06,248:INFO:Uploading model into container now
2025-04-10 19:38:06,248:INFO:_master_model_container: 5
2025-04-10 19:38:06,248:INFO:_display_container: 2
2025-04-10 19:38:06,249:INFO:SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.001, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=-1, penalty='l2',
              power_t=0.5, random_state=123, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)
2025-04-10 19:38:06,249:INFO:create_model() successfully completed......................................
2025-04-10 19:38:06,334:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:06,334:INFO:Creating metrics dataframe
2025-04-10 19:38:06,338:INFO:Initializing Ridge Classifier
2025-04-10 19:38:06,338:INFO:Total runtime is 0.14566507736841838 minutes
2025-04-10 19:38:06,340:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:06,340:INFO:Initializing create_model()
2025-04-10 19:38:06,340:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=ridge, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:06,340:INFO:Checking exceptions
2025-04-10 19:38:06,340:INFO:Importing libraries
2025-04-10 19:38:06,341:INFO:Copying training dataset
2025-04-10 19:38:06,344:INFO:Defining folds
2025-04-10 19:38:06,344:INFO:Declaring metric variables
2025-04-10 19:38:06,346:INFO:Importing untrained model
2025-04-10 19:38:06,347:INFO:Ridge Classifier Imported successfully
2025-04-10 19:38:06,352:INFO:Starting cross validation
2025-04-10 19:38:06,357:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:06,533:INFO:Calculating mean and std
2025-04-10 19:38:06,533:INFO:Creating metrics dataframe
2025-04-10 19:38:06,534:INFO:Uploading results into container
2025-04-10 19:38:06,535:INFO:Uploading model into container now
2025-04-10 19:38:06,535:INFO:_master_model_container: 6
2025-04-10 19:38:06,535:INFO:_display_container: 2
2025-04-10 19:38:06,535:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2025-04-10 19:38:06,535:INFO:create_model() successfully completed......................................
2025-04-10 19:38:06,620:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:06,620:INFO:Creating metrics dataframe
2025-04-10 19:38:06,625:INFO:Initializing Random Forest Classifier
2025-04-10 19:38:06,625:INFO:Total runtime is 0.15044451554616292 minutes
2025-04-10 19:38:06,626:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:06,627:INFO:Initializing create_model()
2025-04-10 19:38:06,627:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=rf, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:06,627:INFO:Checking exceptions
2025-04-10 19:38:06,627:INFO:Importing libraries
2025-04-10 19:38:06,627:INFO:Copying training dataset
2025-04-10 19:38:06,630:INFO:Defining folds
2025-04-10 19:38:06,630:INFO:Declaring metric variables
2025-04-10 19:38:06,632:INFO:Importing untrained model
2025-04-10 19:38:06,633:INFO:Random Forest Classifier Imported successfully
2025-04-10 19:38:06,637:INFO:Starting cross validation
2025-04-10 19:38:06,642:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:07,120:INFO:Calculating mean and std
2025-04-10 19:38:07,120:INFO:Creating metrics dataframe
2025-04-10 19:38:07,121:INFO:Uploading results into container
2025-04-10 19:38:07,122:INFO:Uploading model into container now
2025-04-10 19:38:07,122:INFO:_master_model_container: 7
2025-04-10 19:38:07,122:INFO:_display_container: 2
2025-04-10 19:38:07,122:INFO:RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=123, verbose=0,
                       warm_start=False)
2025-04-10 19:38:07,122:INFO:create_model() successfully completed......................................
2025-04-10 19:38:07,204:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:07,204:INFO:Creating metrics dataframe
2025-04-10 19:38:07,208:INFO:Initializing Quadratic Discriminant Analysis
2025-04-10 19:38:07,209:INFO:Total runtime is 0.16018507480621338 minutes
2025-04-10 19:38:07,211:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:07,211:INFO:Initializing create_model()
2025-04-10 19:38:07,211:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=qda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:07,211:INFO:Checking exceptions
2025-04-10 19:38:07,211:INFO:Importing libraries
2025-04-10 19:38:07,211:INFO:Copying training dataset
2025-04-10 19:38:07,215:INFO:Defining folds
2025-04-10 19:38:07,215:INFO:Declaring metric variables
2025-04-10 19:38:07,216:INFO:Importing untrained model
2025-04-10 19:38:07,218:INFO:Quadratic Discriminant Analysis Imported successfully
2025-04-10 19:38:07,222:INFO:Starting cross validation
2025-04-10 19:38:07,226:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:07,355:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,366:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,370:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,375:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,377:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,377:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,382:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,383:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,390:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,413:WARNING:c:\anaconda3\Lib\site-packages\sklearn\discriminant_analysis.py:935: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")

2025-04-10 19:38:07,432:INFO:Calculating mean and std
2025-04-10 19:38:07,432:INFO:Creating metrics dataframe
2025-04-10 19:38:07,434:INFO:Uploading results into container
2025-04-10 19:38:07,434:INFO:Uploading model into container now
2025-04-10 19:38:07,435:INFO:_master_model_container: 8
2025-04-10 19:38:07,435:INFO:_display_container: 2
2025-04-10 19:38:07,435:INFO:QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
                              store_covariance=False, tol=0.0001)
2025-04-10 19:38:07,435:INFO:create_model() successfully completed......................................
2025-04-10 19:38:07,523:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:07,523:INFO:Creating metrics dataframe
2025-04-10 19:38:07,529:INFO:Initializing Ada Boost Classifier
2025-04-10 19:38:07,529:INFO:Total runtime is 0.16551152467727662 minutes
2025-04-10 19:38:07,531:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:07,531:INFO:Initializing create_model()
2025-04-10 19:38:07,531:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=ada, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:07,531:INFO:Checking exceptions
2025-04-10 19:38:07,531:INFO:Importing libraries
2025-04-10 19:38:07,531:INFO:Copying training dataset
2025-04-10 19:38:07,535:INFO:Defining folds
2025-04-10 19:38:07,535:INFO:Declaring metric variables
2025-04-10 19:38:07,537:INFO:Importing untrained model
2025-04-10 19:38:07,539:INFO:Ada Boost Classifier Imported successfully
2025-04-10 19:38:07,542:INFO:Starting cross validation
2025-04-10 19:38:07,547:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:07,680:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,680:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,685:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,688:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,694:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,696:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,707:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,709:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,709:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,716:WARNING:c:\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(

2025-04-10 19:38:07,951:INFO:Calculating mean and std
2025-04-10 19:38:07,951:INFO:Creating metrics dataframe
2025-04-10 19:38:07,952:INFO:Uploading results into container
2025-04-10 19:38:07,952:INFO:Uploading model into container now
2025-04-10 19:38:07,953:INFO:_master_model_container: 9
2025-04-10 19:38:07,953:INFO:_display_container: 2
2025-04-10 19:38:07,953:INFO:AdaBoostClassifier(algorithm='SAMME.R', estimator=None, learning_rate=1.0,
                   n_estimators=50, random_state=123)
2025-04-10 19:38:07,953:INFO:create_model() successfully completed......................................
2025-04-10 19:38:08,040:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:08,040:INFO:Creating metrics dataframe
2025-04-10 19:38:08,045:INFO:Initializing Gradient Boosting Classifier
2025-04-10 19:38:08,045:INFO:Total runtime is 0.17411980231602986 minutes
2025-04-10 19:38:08,047:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:08,047:INFO:Initializing create_model()
2025-04-10 19:38:08,047:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=gbc, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:08,047:INFO:Checking exceptions
2025-04-10 19:38:08,047:INFO:Importing libraries
2025-04-10 19:38:08,047:INFO:Copying training dataset
2025-04-10 19:38:08,051:INFO:Defining folds
2025-04-10 19:38:08,051:INFO:Declaring metric variables
2025-04-10 19:38:08,053:INFO:Importing untrained model
2025-04-10 19:38:08,055:INFO:Gradient Boosting Classifier Imported successfully
2025-04-10 19:38:08,058:INFO:Starting cross validation
2025-04-10 19:38:08,070:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:09,048:INFO:Calculating mean and std
2025-04-10 19:38:09,048:INFO:Creating metrics dataframe
2025-04-10 19:38:09,049:INFO:Uploading results into container
2025-04-10 19:38:09,050:INFO:Uploading model into container now
2025-04-10 19:38:09,050:INFO:_master_model_container: 10
2025-04-10 19:38:09,050:INFO:_display_container: 2
2025-04-10 19:38:09,050:INFO:GradientBoostingClassifier(ccp_alpha=0.0, criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='log_loss', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_samples_leaf=1,
                           min_samples_split=2, min_weight_fraction_leaf=0.0,
                           n_estimators=100, n_iter_no_change=None,
                           random_state=123, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)
2025-04-10 19:38:09,050:INFO:create_model() successfully completed......................................
2025-04-10 19:38:09,135:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:09,135:INFO:Creating metrics dataframe
2025-04-10 19:38:09,140:INFO:Initializing Linear Discriminant Analysis
2025-04-10 19:38:09,140:INFO:Total runtime is 0.1923600157101949 minutes
2025-04-10 19:38:09,142:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:09,142:INFO:Initializing create_model()
2025-04-10 19:38:09,142:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=lda, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:09,142:INFO:Checking exceptions
2025-04-10 19:38:09,142:INFO:Importing libraries
2025-04-10 19:38:09,142:INFO:Copying training dataset
2025-04-10 19:38:09,146:INFO:Defining folds
2025-04-10 19:38:09,146:INFO:Declaring metric variables
2025-04-10 19:38:09,147:INFO:Importing untrained model
2025-04-10 19:38:09,149:INFO:Linear Discriminant Analysis Imported successfully
2025-04-10 19:38:09,154:INFO:Starting cross validation
2025-04-10 19:38:09,158:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:09,352:INFO:Calculating mean and std
2025-04-10 19:38:09,352:INFO:Creating metrics dataframe
2025-04-10 19:38:09,353:INFO:Uploading results into container
2025-04-10 19:38:09,354:INFO:Uploading model into container now
2025-04-10 19:38:09,354:INFO:_master_model_container: 11
2025-04-10 19:38:09,354:INFO:_display_container: 2
2025-04-10 19:38:09,354:INFO:LinearDiscriminantAnalysis(covariance_estimator=None, n_components=None,
                           priors=None, shrinkage=None, solver='svd',
                           store_covariance=False, tol=0.0001)
2025-04-10 19:38:09,354:INFO:create_model() successfully completed......................................
2025-04-10 19:38:09,440:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:09,440:INFO:Creating metrics dataframe
2025-04-10 19:38:09,445:INFO:Initializing Extra Trees Classifier
2025-04-10 19:38:09,445:INFO:Total runtime is 0.19745149215062457 minutes
2025-04-10 19:38:09,447:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:09,447:INFO:Initializing create_model()
2025-04-10 19:38:09,447:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=et, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:09,448:INFO:Checking exceptions
2025-04-10 19:38:09,448:INFO:Importing libraries
2025-04-10 19:38:09,448:INFO:Copying training dataset
2025-04-10 19:38:09,452:INFO:Defining folds
2025-04-10 19:38:09,452:INFO:Declaring metric variables
2025-04-10 19:38:09,454:INFO:Importing untrained model
2025-04-10 19:38:09,455:INFO:Extra Trees Classifier Imported successfully
2025-04-10 19:38:09,459:INFO:Starting cross validation
2025-04-10 19:38:09,464:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:09,849:INFO:Calculating mean and std
2025-04-10 19:38:09,850:INFO:Creating metrics dataframe
2025-04-10 19:38:09,851:INFO:Uploading results into container
2025-04-10 19:38:09,851:INFO:Uploading model into container now
2025-04-10 19:38:09,851:INFO:_master_model_container: 12
2025-04-10 19:38:09,851:INFO:_display_container: 2
2025-04-10 19:38:09,852:INFO:ExtraTreesClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                     criterion='gini', max_depth=None, max_features='sqrt',
                     max_leaf_nodes=None, max_samples=None,
                     min_impurity_decrease=0.0, min_samples_leaf=1,
                     min_samples_split=2, min_weight_fraction_leaf=0.0,
                     monotonic_cst=None, n_estimators=100, n_jobs=-1,
                     oob_score=False, random_state=123, verbose=0,
                     warm_start=False)
2025-04-10 19:38:09,852:INFO:create_model() successfully completed......................................
2025-04-10 19:38:09,938:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:09,939:INFO:Creating metrics dataframe
2025-04-10 19:38:09,944:INFO:Initializing Light Gradient Boosting Machine
2025-04-10 19:38:09,944:INFO:Total runtime is 0.20575863917668658 minutes
2025-04-10 19:38:09,945:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:09,945:INFO:Initializing create_model()
2025-04-10 19:38:09,945:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=lightgbm, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:09,945:INFO:Checking exceptions
2025-04-10 19:38:09,945:INFO:Importing libraries
2025-04-10 19:38:09,945:INFO:Copying training dataset
2025-04-10 19:38:09,949:INFO:Defining folds
2025-04-10 19:38:09,949:INFO:Declaring metric variables
2025-04-10 19:38:09,950:INFO:Importing untrained model
2025-04-10 19:38:09,952:INFO:Light Gradient Boosting Machine Imported successfully
2025-04-10 19:38:09,956:INFO:Starting cross validation
2025-04-10 19:38:09,961:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:11,215:INFO:Calculating mean and std
2025-04-10 19:38:11,215:INFO:Creating metrics dataframe
2025-04-10 19:38:11,216:INFO:Uploading results into container
2025-04-10 19:38:11,217:INFO:Uploading model into container now
2025-04-10 19:38:11,217:INFO:_master_model_container: 13
2025-04-10 19:38:11,217:INFO:_display_container: 2
2025-04-10 19:38:11,218:INFO:LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=123, reg_alpha=0.0, reg_lambda=0.0, subsample=1.0,
               subsample_for_bin=200000, subsample_freq=0)
2025-04-10 19:38:11,218:INFO:create_model() successfully completed......................................
2025-04-10 19:38:11,308:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:11,308:INFO:Creating metrics dataframe
2025-04-10 19:38:11,313:INFO:Initializing Dummy Classifier
2025-04-10 19:38:11,313:INFO:Total runtime is 0.22858298619588213 minutes
2025-04-10 19:38:11,315:INFO:SubProcess create_model() called ==================================
2025-04-10 19:38:11,315:INFO:Initializing create_model()
2025-04-10 19:38:11,315:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=dummy, fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=<pycaret.internal.display.display.CommonDisplay object at 0x000001DB3423F190>, model_only=True, return_train_score=False, error_score=raise, kwargs={})
2025-04-10 19:38:11,316:INFO:Checking exceptions
2025-04-10 19:38:11,316:INFO:Importing libraries
2025-04-10 19:38:11,316:INFO:Copying training dataset
2025-04-10 19:38:11,319:INFO:Defining folds
2025-04-10 19:38:11,319:INFO:Declaring metric variables
2025-04-10 19:38:11,321:INFO:Importing untrained model
2025-04-10 19:38:11,322:INFO:Dummy Classifier Imported successfully
2025-04-10 19:38:11,326:INFO:Starting cross validation
2025-04-10 19:38:11,330:INFO:Cross validating with StratifiedKFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2025-04-10 19:38:11,466:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,469:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,479:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,479:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (146, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,481:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,482:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,482:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,484:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,497:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,499:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,500:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,500:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,501:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,502:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,502:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,503:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,514:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,516:WARNING:c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py:204: FitFailedWarning: Metric 'make_scorer(roc_auc_score, response_method=('decision_function', 'predict_proba'), average=weighted, multi_class=ovr)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 196, in _score
    return super()._score(
           ^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_scorer.py", line 350, in _score
    return self._sign * self._score_func(y_true, y_pred, **scoring_kwargs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\pycaret\internal\metrics.py", line 144, in __call__
    return self.score_func(y_true, y_pred, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 213, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 640, in roc_auc_score
    return _average_binary_score(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_base.py", line 75, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 387, in _binary_roc_auc_score
    fpr, tpr, _ = roc_curve(y_true, y_score, sample_weight=sample_weight)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 186, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 1108, in roc_curve
    fps, tps, thresholds = _binary_clf_curve(
                           ^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\metrics\_ranking.py", line 821, in _binary_clf_curve
    y_score = column_or_1d(y_score)
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\anaconda3\Lib\site-packages\sklearn\utils\validation.py", line 1367, in column_or_1d
    raise ValueError(
ValueError: y should be a 1d array, got an array of shape (147, 2) instead.

  warnings.warn(

2025-04-10 19:38:11,517:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,518:WARNING:c:\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

2025-04-10 19:38:11,523:INFO:Calculating mean and std
2025-04-10 19:38:11,523:INFO:Creating metrics dataframe
2025-04-10 19:38:11,525:INFO:Uploading results into container
2025-04-10 19:38:11,526:INFO:Uploading model into container now
2025-04-10 19:38:11,526:INFO:_master_model_container: 14
2025-04-10 19:38:11,526:INFO:_display_container: 2
2025-04-10 19:38:11,526:INFO:DummyClassifier(constant=None, random_state=123, strategy='prior')
2025-04-10 19:38:11,526:INFO:create_model() successfully completed......................................
2025-04-10 19:38:11,613:INFO:SubProcess create_model() end ==================================
2025-04-10 19:38:11,613:INFO:Creating metrics dataframe
2025-04-10 19:38:11,623:INFO:Initializing create_model()
2025-04-10 19:38:11,623:INFO:create_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), fold=StratifiedKFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, probability_threshold=None, experiment_custom_tags=None, verbose=False, system=False, add_to_model_list=True, metrics=None, display=None, model_only=True, return_train_score=False, error_score=0.0, kwargs={})
2025-04-10 19:38:11,623:INFO:Checking exceptions
2025-04-10 19:38:11,624:INFO:Importing libraries
2025-04-10 19:38:11,624:INFO:Copying training dataset
2025-04-10 19:38:11,628:INFO:Defining folds
2025-04-10 19:38:11,628:INFO:Declaring metric variables
2025-04-10 19:38:11,628:INFO:Importing untrained model
2025-04-10 19:38:11,628:INFO:Declaring custom model
2025-04-10 19:38:11,628:INFO:Ridge Classifier Imported successfully
2025-04-10 19:38:11,632:INFO:Cross validation set to False
2025-04-10 19:38:11,632:INFO:Fitting Model
2025-04-10 19:38:11,743:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2025-04-10 19:38:11,743:INFO:create_model() successfully completed......................................
2025-04-10 19:38:11,841:INFO:_master_model_container: 14
2025-04-10 19:38:11,842:INFO:_display_container: 2
2025-04-10 19:38:11,842:INFO:RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001)
2025-04-10 19:38:11,842:INFO:compare_models() successfully completed......................................
2025-04-10 19:48:50,162:INFO:Initializing save_model()
2025-04-10 19:48:50,162:INFO:save_model(model=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), model_name=Project\pycaret_first_results_best_model, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\JOS~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcceptedCmp1', 'AcceptedCmp2',
                                             'AcceptedCmp3', 'AcceptedCmp4',
                                             'AcceptedCmp5', 'Age', 'Complain',
                                             'Income', 'Kidhome',
                                             'MntFishProducts', 'MntFruits',
                                             'MntGoldProds', 'MntMeatProducts',
                                             'MntSweetProducts', 'MntWines'...
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('remove_outliers',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=RemoveOutliers(method='iforest',
                                                               n_jobs=1,
                                                               random_state=123,
                                                               threshold=0.05))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              random_state=123,
                                                                              sampling_strategy='auto'))))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2025-04-10 19:48:50,162:INFO:Adding model into prep_pipe
2025-04-10 19:48:50,187:INFO:Project\pycaret_first_results_best_model.pkl saved in current working directory
2025-04-10 19:48:50,191:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcceptedCmp1', 'AcceptedCmp2',
                                             'AcceptedCmp3', 'AcceptedCmp4',
                                             'AcceptedCmp5', 'Age', 'Complain',
                                             'Income', 'Kidhome',
                                             'MntFishProducts', 'MntFruits',
                                             'MntGoldProds', 'MntMeatProducts',
                                             'MntSweetProducts', 'MntWines',
                                             'NumCatalogPurchases',
                                             'NumDealsPurchase...
                                                               threshold=0.05))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              random_state=123,
                                                                              sampling_strategy='auto')))),
                ('trained_model',
                 RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                 fit_intercept=True, max_iter=None,
                                 positive=False, random_state=123,
                                 solver='auto', tol=0.0001))],
         verbose=False)
2025-04-10 19:48:50,191:INFO:save_model() successfully completed......................................
2025-04-10 19:49:25,391:INFO:Initializing save_model()
2025-04-10 19:49:25,391:INFO:save_model(model=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), model_name=Project\pycaret_first_results_best_model, prep_pipe_=Pipeline(memory=FastMemory(location=C:\Users\JOS~1\AppData\Local\Temp\joblib),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcceptedCmp1', 'AcceptedCmp2',
                                             'AcceptedCmp3', 'AcceptedCmp4',
                                             'AcceptedCmp5', 'Age', 'Complain',
                                             'Income', 'Kidhome',
                                             'MntFishProducts', 'MntFruits',
                                             'MntGoldProds', 'MntMeatProducts',
                                             'MntSweetProducts', 'MntWines'...
                                                              use_cat_names=True,
                                                              verbose=0))),
                ('remove_outliers',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=RemoveOutliers(method='iforest',
                                                               n_jobs=1,
                                                               random_state=123,
                                                               threshold=0.05))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              random_state=123,
                                                                              sampling_strategy='auto'))))],
         verbose=False), verbose=True, use_case=MLUsecase.CLASSIFICATION, kwargs={})
2025-04-10 19:49:25,391:INFO:Adding model into prep_pipe
2025-04-10 19:49:25,416:INFO:Project\pycaret_first_results_best_model.pkl saved in current working directory
2025-04-10 19:49:25,420:INFO:Pipeline(memory=Memory(location=None),
         steps=[('numerical_imputer',
                 TransformerWrapper(exclude=None,
                                    include=['AcceptedCmp1', 'AcceptedCmp2',
                                             'AcceptedCmp3', 'AcceptedCmp4',
                                             'AcceptedCmp5', 'Age', 'Complain',
                                             'Income', 'Kidhome',
                                             'MntFishProducts', 'MntFruits',
                                             'MntGoldProds', 'MntMeatProducts',
                                             'MntSweetProducts', 'MntWines',
                                             'NumCatalogPurchases',
                                             'NumDealsPurchase...
                                                               threshold=0.05))),
                ('balance',
                 TransformerWrapper(exclude=None, include=None,
                                    transformer=FixImbalancer(estimator=SMOTE(k_neighbors=5,
                                                                              random_state=123,
                                                                              sampling_strategy='auto')))),
                ('trained_model',
                 RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                 fit_intercept=True, max_iter=None,
                                 positive=False, random_state=123,
                                 solver='auto', tol=0.0001))],
         verbose=False)
2025-04-10 19:49:25,420:INFO:save_model() successfully completed......................................
2025-04-10 19:51:08,125:INFO:Initializing plot_model()
2025-04-10 19:51:08,126:INFO:plot_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), plot=threshold, scale=1, save=False, fold=None, fit_kwargs=None, plot_kwargs=None, groups=None, feature_name=None, label=False, verbose=True, system=True, display=None, display_format=None)
2025-04-10 19:51:08,126:INFO:Checking exceptions
2025-04-10 19:51:08,129:INFO:Preloading libraries
2025-04-10 19:51:08,129:INFO:Copying training dataset
2025-04-10 19:51:08,129:INFO:Plot type: threshold
2025-04-10 19:51:08,300:INFO:Fitting Model
2025-04-10 19:51:08,539:INFO:Scoring test/hold-out set
2025-04-10 19:51:08,748:INFO:Visual Rendered Successfully
2025-04-10 19:51:08,846:INFO:plot_model() successfully completed......................................
2025-04-10 19:51:19,275:INFO:Initializing plot_model()
2025-04-10 19:51:19,276:INFO:plot_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), plot=confusion_matrix, scale=1, save=False, fold=None, fit_kwargs=None, plot_kwargs=None, groups=None, feature_name=None, label=False, verbose=True, system=True, display=None, display_format=None)
2025-04-10 19:51:19,276:INFO:Checking exceptions
2025-04-10 19:51:19,279:INFO:Preloading libraries
2025-04-10 19:51:19,279:INFO:Copying training dataset
2025-04-10 19:51:19,279:INFO:Plot type: confusion_matrix
2025-04-10 19:51:19,451:INFO:Fitting Model
2025-04-10 19:51:19,451:INFO:Scoring test/hold-out set
2025-04-10 19:51:19,503:INFO:Visual Rendered Successfully
2025-04-10 19:51:19,594:INFO:plot_model() successfully completed......................................
2025-04-10 19:52:06,811:INFO:Initializing plot_model()
2025-04-10 19:52:06,811:INFO:plot_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), plot=feature, scale=1, save=False, fold=None, fit_kwargs=None, plot_kwargs=None, groups=None, feature_name=None, label=False, verbose=True, system=True, display=None, display_format=None)
2025-04-10 19:52:06,811:INFO:Checking exceptions
2025-04-10 19:52:06,815:INFO:Preloading libraries
2025-04-10 19:52:06,815:INFO:Copying training dataset
2025-04-10 19:52:06,815:INFO:Plot type: feature
2025-04-10 19:52:06,950:INFO:Visual Rendered Successfully
2025-04-10 19:52:07,044:INFO:plot_model() successfully completed......................................
2025-04-10 19:52:24,869:INFO:Initializing plot_model()
2025-04-10 19:52:24,869:INFO:plot_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), plot=pr, scale=1, save=False, fold=None, fit_kwargs=None, plot_kwargs=None, groups=None, feature_name=None, label=False, verbose=True, system=True, display=None, display_format=None)
2025-04-10 19:52:24,870:INFO:Checking exceptions
2025-04-10 19:52:24,874:INFO:Preloading libraries
2025-04-10 19:52:24,874:INFO:Copying training dataset
2025-04-10 19:52:24,875:INFO:Plot type: pr
2025-04-10 19:52:25,048:INFO:Fitting Model
2025-04-10 19:52:25,049:INFO:Scoring test/hold-out set
2025-04-10 19:52:25,125:INFO:Visual Rendered Successfully
2025-04-10 19:52:25,222:INFO:plot_model() successfully completed......................................
2025-04-10 19:52:47,236:INFO:Initializing predict_model()
2025-04-10 19:52:47,236:INFO:predict_model(self=<pycaret.classification.oop.ClassificationExperiment object at 0x000001DB31965DD0>, estimator=RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True, fit_intercept=True,
                max_iter=None, positive=False, random_state=123, solver='auto',
                tol=0.0001), probability_threshold=None, encoded_labels=False, raw_score=True, round=4, verbose=True, ml_usecase=None, preprocess=True, encode_labels=<function _SupervisedExperiment.predict_model.<locals>.encode_labels at 0x000001DB36607CE0>)
2025-04-10 19:52:47,236:INFO:Checking exceptions
2025-04-10 19:52:47,236:INFO:Preloading libraries
2025-04-10 19:52:47,239:INFO:Set up data.
2025-04-10 19:52:47,244:INFO:Set up index.
